NRCan/datahub-portal

WebPortal/Controllers/PublicController.cs

This controller should allow unauthenticated access to a few urls:
- [base]/Public/HelloWorld - simple hello world message
- [base]/Public/DataLakeTest - serve a file from data lake storage
- [base]/Public/BlobTest - serve a file from blob storage

Unauthenticated access test controller

---

Datahub.Core/Migrations/Core/20210914174729_DataProjectDbColumns.Designer.cs
Datahub.Core/Migrations/Core/20210914174729_DataProjectDbColumns.cs
Datahub.Core/Model/Datahub/DatahubProjectDBContext.cs
Datahub.Core/Model/Datahub/Datahub_Project.cs

Added migration for additional columns in Projects
DB_Name, DB_Server and DB_Type

Database columns in Projects table

---

Datahub.Core/Model/Datahub/Datahub_Project.cs
Datahub.Core/Services/IProjectDatabaseService.cs
Datahub.Core/Services/ProjectDatabaseService.cs
WebPortal/Pages/DataProject.razor
WebPortal/Startup.cs
WebPortal/Views/DataProjectDbInformation.razor
WebPortal/i18n/localization.json

Added a card that shows database information when the project has an associated database. Popup shows more information and allows the logged in user to get a Postgres access token

Postgres token prototype

---

Datahub.Core/Migrations/Core/20211018184834_AddingChoices.Designer.cs
Datahub.Core/Migrations/Core/20211018184834_AddingChoices.cs
Datahub.Core/Model/Datahub/WebForm_Field.cs
Datahub.Core/Utils/FieldCodeGenerator.cs
DatahubTest/Forms/FieldCodeGeneratorTests.cs
WebPortal/Pages/FormBuilder/ViewField.razor
WebPortal/Pages/FormBuilder/ViewForm.razor
WebPortal/Pages/Forms/ShareWorkflow/ApprovalForm.razor

Add choices to Form Fields and implement the corresponding C# code generation

Adding choices to Form Fields and implement the corresponding code generation

---

Datahub.CKAN/Package/PackageGenerator.cs
Datahub.CKAN/Service/CKANService.cs
Datahub.CKAN/Service/ICKANService.cs
Datahub.Metadata/DTO/FieldValueContainer.cs
Datahub.Metadata/Migrations/20211104150643_AddFieldDefaultValue.Designer.cs
Datahub.Metadata/Migrations/20211104150643_AddFieldDefaultValue.cs
Datahub.Metadata/Model/FieldDefinition.cs
DatahubTest/CKAN/CKANPakageBuilderTest.cs
WebPortal/Components/Metadata/MetadataEditor.razor
WebPortal/Components/Metadata/MetadataFieldEditor.razor
WebPortal/Components/Metadata/ObjectMetadataEditor.razor
WebPortal/Pages/MetadataPage.razor
WebPortal/Pages/ShareOpenData.razor

- I am not done with this feature, but it should not affect any other feature. 
- This branch contains the latest migrations in the Metadata DB so we can update prod's Field Definitions.

Develop metadata opendata integration

---

Datahub.Core/Services/MSGraphService.cs
WebPortal/Data/Forms/PIP/PIP_IndicatorAndResults.cs
WebPortal/Data/Forms/PIP/PIP_Risks.cs
WebPortal/Data/Forms/PIP/PIP_Tombstone.cs
WebPortal/Migrations/Forms/PIP/20211213192842_newpipfields.Designer.cs
WebPortal/Migrations/Forms/PIP/20211213192842_newpipfields.cs

Hello, i need to add a fix to my msgraph service, please verify

Pip version2

---

WebPortal/Components/Metadata/KeywordInput.razor
WebPortal/Components/Metadata/MetadataEditor.razor
WebPortal/Components/Metadata/ObjectMetadataEditor.razor
WebPortal/Pages/ShareOpenData.razor
WebPortal/Pages/SharingWorkflow.razor
WebPortal/i18n/localization.fr.json
WebPortal/i18n/localization.json

- Color of Translated text note
- Added a tool tip and location of suggested keywords
- Make space for Show/Hide Optional Fields button and properly align with fields.
- Collapse the Approval form when re-editing the Metadata and vice-versa.
- Matching the title of the left with the step in the right when possible.
- Add an explanation on what to do with the generated PDF
- Adding minimal validation on the GDocs URL

#3083 Multiple wizard improvements

---

Datahub.Core/Services/CognitiveSearchService.cs
Datahub.Core/Services/ICognitiveSearchService.cs
Datahub.Core/Services/Offline/OfflineCognitiveSearchService.cs
WebPortal/Components/AddDataBar.razor
WebPortal/Components/FileGridComponents/FileGrid.razor
WebPortal/Components/FileGridComponents/FileGridMenu.razor
WebPortal/Layout/PortalLayout.razor
WebPortal/Pages/AddDataPage.razor
WebPortal/Pages/Tools.razor
WebPortal/appsettings.Development.json-tmpl

- project fixes for upload
- indexing improvement for my files
- new cataloguing report in tools

Upload fixes and powerbi report for cataloguing

---

Datahub.Core/Services/EmailNotificationService.cs
Datahub.Core/Services/IEmailNotificationService.cs
Datahub.Core/Templates/LanguageTraining/LSUExcessInDemand.razor

Sending language school decision in one email with two recipients

---

Datahub.Core/Services/IPortalVersionService.cs
WebPortal/Datahub.Portal.csproj
WebPortal/Pages/Debug.razor
WebPortal/Services/PortalVersionService.cs
WebPortal/Startup.cs

Note: Reading the ENV VARS is breaking the pipeline, reading the release info from the settings for now.

Displaying the Release Version info from the App Config values

---

Datahub.Core/Datahub.Core.csproj
Datahub.Core/Layout/ExternalLayout.razor
Datahub.Core/Services/Storage/IMyDataService.cs
Datahub.Core/Services/Storage/MyDataService.cs
WebPortal/Pages/PowerBI/PowerBIEmbeddedExternal.razor
WebPortal/Services/Api/PowerBiServiceApi.cs
WebPortal/Services/Offline/OfflineMyDataService.cs
WebPortal/wwwroot/js/pbi-integration.js

Adds a page to test generation of embed tokens. If this works, the tokens can be used to share reports externally

Test for Power BI Embed tokens

---

Datahub.Core/Services/IPowerBiDataService.cs
Datahub.Core/Services/PowerBiDataService.cs
WebPortal/Pages/PowerBI/PowerBIConsent.razor
WebPortal/Pages/Project/PowerBiReports/ExternalReportRequest.razor

added configurable token for external sharing
added revoke workflow

revoke workflow

---

WebPortal/Pages/Project/FileExplorer/FileProperties.razor

Cataloging Storage files while editing the metadata

---

Datahub.Core/Services/IMetadataBrokerService.cs
Datahub.Core/Services/MetadataBrokerService.cs
WebPortal/Pages/Admin/PowerBIAdmin.razor
WebPortal/i18n/nrcan/initiatives.fr.json
WebPortal/i18n/nrcan/initiatives.json

- remove catalog entries for deleted items
- updated wording in confirmation dialog

Minor issues from demo

---

CatalogIngestTool/Program.cs
Datahub.Core/Layout/MainLayout.razor
Datahub.Core/Services/DatahubTelemetryAuditingService.cs
Datahub.Core/Services/IDatahubAuditingService.cs
Datahub.Core/Services/IMetadataBrokerService.cs
Datahub.Core/Services/MetadataBrokerService.cs
WebPortal/Components/Metadata/ObjectMetadataEditor.razor
WebPortal/Pages/Admin/PowerBIAdmin.razor
WebPortal/Pages/Catalog/DiscoverySearch.razor
WebPortal/Pages/Catalog/DiscoverySearchLanding.razor
WebPortal/Pages/Catalog/MetadataEditDefinitionPage.razor
WebPortal/Pages/Project/DataProject/DataProjectPage.razor
WebPortal/Pages/ShareOpenData.razor

- Grouping PBI reports and setting the report language
- Fixing issue with catalog upload

Grouping PBI reports and setting the report language

---

WebPortal/Data/Forms/ShareWorkflow/ApprovalForm.cs
WebPortal/Datahub.Portal.csproj
WebPortal/Pages/Forms/ShareWorkflow/ApprovalForm.razor

Only issue is the heading text overlapping on the checkbox fields. Currently I don't think there's a way to disable that for checkboxes.

Open Data approval form converted to MudBlazor

---

Datahub.Core/Components/TopBar/GuestModeToggler.razor
Datahub.Core/Components/TopBar/NotificationsList.razor
Datahub.Core/Components/TopBar/Profile.razor
Datahub.Core/Components/TopBar/Topbar.razor
Datahub.Core/Services/IUserInformationService.cs
Datahub.Core/Services/Offline/OfflineUserInformationService.cs
Datahub.Core/Services/UserInformationService.cs
WebPortal/Pages/Tools/Tools.razor

- moved tools in profile
- improved APIs
- added visitor view

Topbar improvements

---

Datahub.Metadata/Migrations/20220901160934_AddingProjectIdToCatalog.Designer.cs
Datahub.Metadata/Migrations/20220901160934_AddingProjectIdToCatalog.cs
Datahub.Metadata/Model/CatalogObject.cs
Datahub.Metadata/Model/CatalogObjectLanguage.cs
WebPortal/Components/Metadata/ObjectMetadataEditor.razor
WebPortal/Pages/Project/DataProject/ProjectInfo.razor
WebPortal/Pages/Project/DataProjects.razor

+ Misc Initiatives page UI changes

#3619 Modifying the Catalog to include the project id

---

Datahub.Core/Services/IMetadataBrokerService.cs
Datahub.Core/Services/MetadataBrokerService.cs
WebPortal/Components/Metadata/ObjectMetadataEditor.razor
WebPortal/Pages/Catalog/DiscoverySearch.razor
WebPortal/Pages/ShareOpenData.razor

- Filtering Power BI Workspaces and Datases in Catalog search

Adding Catalog object to the search index when added

---

Datahub.Achievements/AchievementService.cs
Datahub.Core/Components/TopBar/NotificationsList.razor

userId was treated as case *sensitive*
userId is now added to db as case *insensitive*

Fix for Achievement userId case sensitivity

---

Datahub.Core/Services/IOrganizationLevelsService.cs
Datahub.Core/Services/IPowerBiDataService.cs
Datahub.Core/Services/Offline/OfflinePowerBiDataService.cs
Datahub.Core/Services/OrganizationLevelsService.cs
Datahub.Core/Services/PowerBiDataService.cs
WebPortal/Pages/InternalPublic/InternalPublishedPowerBiReportEmbeddedPage.razor
WebPortal/Pages/PowerBI/InternalPublishedPowerBIReportLinks.razor
WebPortal/Pages/PowerBI/InternalPublishedPowerBiReportEmbeddedPage.razor
WebPortal/Pages/Project/PowerBiReportsList.razor
WebPortal/i18n/localization.fr.json
WebPortal/i18n/localization.json
WebPortal/i18n/nrcan/initiatives.fr.json
WebPortal/i18n/nrcan/initiatives.json

- display page for Power BI reports, with report info, keywords and sensitivity level
- links for EN/FR versions of reports in the powerbi report list

Powerbi internal published reports

---

Datahub.Core/Components/TopBar/GuestModeToggler.razor
Datahub.Core/Layout/ExternalLayout.razor
Datahub.Core/Layout/InternalLayout.razor
Datahub.Core/Layout/MainLayout.razor
Datahub.Core/Services/AzureCosting/AzureCostManagementService.cs
Datahub.Core/Services/IUserInformationService.cs
Datahub.Core/Services/Offline/OfflineUserInformationService.cs
Datahub.Core/Services/UserInformationService.cs
Datahub.Finance/Pages/FundCenters.razor
Datahub.Graph.Functions/UpdateProjectMonthlyCost.cs
WebPortal/Pages/Admin/Administration.razor
WebPortal/Pages/Admin/FetchProjectsMonthlyCost.razor
WebPortal/Pages/Debug.razor
WebPortal/Pages/Project/DataProject/DataProjectPage.razor
WebPortal/Pages/Project/DataProject/ProjectInfo.razor
WebPortal/Pages/Project/DataProject/ProjectTools/PowerBI.razor
WebPortal/Pages/Project/DataProject/ProjectTools/ProjectToolListing.razor

- caching for auth user
- hiding cost stuff when there is no budget

added caching for authorized user

---

Datahub.Core/wwwroot/css/site.css
WebPortal/Pages/Project/DataProject/DataProjectPage.razor
WebPortal/Pages/Project/DataProject/ProjectMembers.razor
WebPortal/Pages/Project/DataProject/ProjectTools/PowerBI.razor
WebPortal/Pages/Project/DataProject/ProjectTools/ProjectToolListing.razor
WebPortal/i18n/localization.fr.json
WebPortal/i18n/localization.json
WebPortal/i18n/nrcan/initiatives.fr.json
WebPortal/i18n/nrcan/initiatives.json

- reorganized the "request access" to initiative
- fixed css to show data catalog items in right place when not a member
- reworded the access

Fixes for non member view of initiative

---

Datahub.Core/Components/TopBar/Topbar.razor
WebPortal/Pages/Project/DataProject/ProjectCatalog.razor
WebPortal/Pages/Tools/Tools.razor
WebPortal/i18n/localization.fr.json

fix: renamed public datasets to shared datasets
fix: disabled breadcrumbs because of inconsistent names
fix: removed old tiles in tools

minor fixes for prod deployment
